// Static constants: i18n strings, rating bands, sector list. No data here.

// Bilingual UI strings. Access via t('key', lang) from helpers.
window.STR = {
  site_name:        { en: 'Ledger Lens',           th: 'Ledger Lens' },
  tagline:          { en: 'Plain-English equity research, one company a day',
                      th: 'วิเคราะห์หุ้นรายบริษัท อ่านง่าย วันละตัว' },
  nav_home:         { en: 'Home',                  th: 'หน้าแรก' },
  nav_all:          { en: 'All analyses',          th: 'บทวิเคราะห์ทั้งหมด' },
  latest:           { en: 'Latest analyses',       th: 'บทวิเคราะห์ล่าสุด' },
  read:             { en: 'Read',                  th: 'อ่านต่อ' },
  as_of:            { en: 'As of',                 th: 'ข้อมูล ณ' },
  market_cap:       { en: 'Market Cap',            th: 'มูลค่าตลาด' },
  sector:           { en: 'Sector',                th: 'กลุ่มธุรกิจ' },

  sec_overview:     { en: 'Business Overview',     th: 'ภาพรวมธุรกิจ' },
  sec_performance:  { en: 'Revenue & Profit',      th: 'รายได้และกำไร' },
  sec_margins:      { en: 'Margin Trend',          th: 'แนวโน้มอัตรากำไร' },
  sec_segments:     { en: 'Business Segments',     th: 'ธุรกิจย่อย' },
  sec_valuation:    { en: 'Valuation',             th: 'การประเมินมูลค่า' },
  sec_balance:      { en: 'Balance Sheet Health',  th: 'สุขภาพงบดุล' },
  sec_analyst:      { en: 'Analyst Consensus',     th: 'มุมมองนักวิเคราะห์' },
  sec_filing:       { en: 'Latest Filing',         th: 'รายงานล่าสุด' },
  sec_catalysts:    { en: 'Growth Catalysts',      th: 'ปัจจัยหนุน' },
  sec_risks:        { en: 'Risk Factors',          th: 'ปัจจัยเสี่ยง' },
  sec_take:         { en: 'Our Take',              th: 'มุมมองของเรา' },

  m_revenue:        { en: 'Revenue',               th: 'รายได้' },
  m_gross_profit:   { en: 'Gross Profit',          th: 'กำไรขั้นต้น' },
  m_op_income:      { en: 'Operating Income',      th: 'กำไรจากดำเนินงาน' },
  m_net_income:     { en: 'Net Income',            th: 'กำไรสุทธิ' },
  m_gross_margin:   { en: 'Gross Margin',          th: 'อัตรากำไรขั้นต้น' },
  m_op_margin:      { en: 'Operating Margin',      th: 'อัตรากำไรดำเนินงาน' },
  m_net_margin:     { en: 'Net Margin',            th: 'อัตรากำไรสุทธิ' },
  m_revenue_growth: { en: 'Revenue Growth',        th: 'การเติบโตรายได้' },
  chart_both:       { en: 'Revenue + Profit',      th: 'รายได้ + กำไร' },
  chart_yoy_hint:   { en: '% = year-over-year change', th: '% = เปลี่ยนแปลงเทียบปีก่อน' },
  m_pe:             { en: 'P/E',                    th: 'P/E' },
  m_fwd_pe:         { en: 'Forward P/E',           th: 'P/E ล่วงหน้า' },
  m_ps:             { en: 'P/S',                    th: 'P/S' },
  m_pb:             { en: 'P/B',                    th: 'P/B' },
  m_ev_ebitda:      { en: 'EV/EBITDA',             th: 'EV/EBITDA' },
  m_peg:            { en: 'PEG',                    th: 'PEG' },
  m_5y_avg:         { en: '5Y Avg',                th: 'เฉลี่ย 5 ปี' },
  m_cash:           { en: 'Cash',                  th: 'เงินสด' },
  m_debt:           { en: 'Total Debt',            th: 'หนี้สินรวม' },
  m_de:             { en: 'Debt / Equity',         th: 'หนี้สินต่อทุน' },
  m_current:        { en: 'Current Ratio',         th: 'อัตราส่วนสภาพคล่อง' },
  m_coverage:       { en: 'Interest Coverage',     th: 'ความสามารถจ่ายดอกเบี้ย' },
  m_assets:         { en: 'Assets',                th: 'สินทรัพย์' },
  m_capex:          { en: 'Capex',                 th: 'เงินลงทุน' },

  price_target:     { en: 'Price Target',          th: 'ราคาเป้าหมาย' },
  current_price:    { en: 'Current Price',         th: 'ราคาปัจจุบัน' },
  segment_set:      { en: 'View',                  th: 'มุมมอง' },
  segment_metric:   { en: 'Metric',                th: 'ตัวชี้วัด' },
  segment_focus:    { en: 'Focus',                 th: 'เลือกธุรกิจ' },
  segment_all:      { en: 'All businesses',        th: 'ทุกธุรกิจ' },
  segment_view:     { en: 'Segment chart view',    th: 'มุมมองกราฟธุรกิจย่อย' },
  segment_absolute: { en: 'Absolute',              th: 'มูลค่า' },
  segment_mix:      { en: 'Mix %',                 th: 'สัดส่วน %' },
  segment_business: { en: 'Business',              th: 'ธุรกิจ' },
  segment_share:    { en: 'Share',                 th: 'สัดส่วน' },
  segment_cagr:     { en: 'CAGR',                  th: 'CAGR' },
  segment_disclosure:{ en: 'Disclosure quality',   th: 'คุณภาพการเปิดเผยข้อมูล' },
  segment_not_disclosed:{ en: 'This metric is not disclosed.', th: 'บริษัทไม่ได้เปิดเผยตัวชี้วัดนี้' },
  metric:           { en: 'Metric',                th: 'ตัวชี้วัด' },
  current:          { en: 'Current',                th: 'ปัจจุบัน' },
  vs_peer:          { en: 'vs Peers',              th: 'เทียบคู่แข่ง' },

  empty:            { en: 'No analyses published yet.', th: 'ยังไม่มีบทวิเคราะห์' },
  loading:          { en: 'Loading…',              th: 'กำลังโหลด…' },
  back:             { en: '← Back',                 th: '← กลับ' },
  disclaimer:       { en: 'For educational purposes only. Not investment advice.',
                      th: 'เพื่อการศึกษาเท่านั้น ไม่ใช่คำแนะนำการลงทุน' },

  // New UI specific keys
  rating_bull:      { en: 'Bull',                  th: 'เชิงบวก' },
  rating_neutral:   { en: 'Neutral',               th: 'เป็นกลาง' },
  rating_bear:      { en: 'Bear',                  th: 'เชิงลบ' },
  sort_mcap:        { en: 'Market cap',            th: 'มูลค่าตลาด' },
  sort_upside:      { en: 'Upside',                th: 'อัพไซด์' },
  rating_sbuy:      { en: 'Strong Buy',            th: 'ซื้อมาก' },
  rating_buy:       { en: 'Buy',                   th: 'ซื้อ' },
  rating_hold:      { en: 'Hold',                  th: 'ถือ' },
  rating_sell:      { en: 'Sell',                  th: 'ขาย' },
  rating_ssell:     { en: 'Strong Sell',           th: 'ขายมาก' },
  turn_positive:    { en: 'Turn positive',         th: 'พลิกบวก' },
  turn_negative:    { en: 'Turn negative',         th: 'พลิกลบ' },
  disclosure_grade_title: { en: 'Disclosure grade', th: 'คุณภาพการเปิดเผยข้อมูลเกรด' },
  undisclosed:      { en: 'Undisclosed',           th: 'ไม่เปิดเผย' },
  price_label:      { en: 'Price',                 th: 'ราคา' },
  rev_5y_label:     { en: '5Y Revenue',            th: 'รายได้ 5 ปี' },
  analyzed_at:      { en: 'Analyzed at',           th: 'วิเคราะห์' },
  view_analysis:    { en: 'View research',         th: 'ดูบทวิเคราะห์' },
  c_kr:             { en: 'South Korea',           th: 'เกาหลีใต้' },
  c_us:             { en: 'United States',         th: 'สหรัฐอเมริกา' },
  c_hk:             { en: 'China / Hong Kong',     th: 'ฮ่องกง/จีน' },
  c_th:             { en: 'Thailand',              th: 'ไทย' },
  c_jp:             { en: 'Japan',                 th: 'ญี่ปุ่น' },
  c_tw:             { en: 'Taiwan',                th: 'ไต้หวัน' },
  c_fi:             { en: 'Finland',               th: 'ฟินแลนด์' },
  c_gb:             { en: 'United Kingdom',        th: 'สหราชอาณาจักร' },
  c_nl:             { en: 'Netherlands',           th: 'เนเธอร์แลนด์' },
  latest_research_eyebrow: { en: 'Latest equity research', th: 'บทวิเคราะห์ล่าสุด' },
  search_placeholder: { en: 'Search ticker or company name...', th: 'ค้นหา ticker หรือชื่อบริษัท…' },
  clear_filters:    { en: 'Clear',                  th: 'ล้างตัวกรอง' },
  empty_state_title: { en: 'No analyses found',     th: 'ไม่พบบทวิเคราะห์ที่ตรงกัน' },
  empty_state_desc:  { en: 'Try changing search term or clearing filters', th: 'ลองเปลี่ยนคำค้นหรือล้างตัวกรอง แล้วลองใหม่อีกครั้ง' },
  error_state_title: { en: 'Failed to load analyses', th: 'โหลดข้อมูลไม่สำเร็จ' },
  error_state_desc:  { en: 'An error occurred while connecting to database. Please try again.', th: 'เกิดข้อผิดพลาดในการเชื่อมต่อกับฐานข้อมูลบทวิเคราะห์ กรุณาลองใหม่อีกครั้ง' },
  retry_btn:         { en: 'Retry',                 th: 'ลองใหม่' },
  price_asof_date:   { en: 'Price as of analysis date', th: 'ราคา ณ วันที่วิเคราะห์' },
  analysis_date_label: { en: 'Analysis date',       th: 'วันที่วิเคราะห์' },
  forward_pe_label:  { en: 'Forward P/E',          th: 'P/E ล่วงหน้า' },
  pe_label:          { en: 'P/E',                  th: 'P/E' },
  our_view_title:    { en: 'Our View',              th: 'มุมมองของเรา' },
  q_interesting:     { en: 'Is this stock interesting?', th: 'หุ้นนี้น่าสนใจไหม?' },
  q_margin:          { en: 'Are profit margins improving?', th: 'กำไร / margin ดีขึ้นหรือแย่ลง?' },
  q_mainBiz:         { en: 'Which business is the main driver?', th: 'ธุรกิจไหนทำเงินหลัก?' },
  q_valuation:       { en: 'Is the valuation cheap or expensive?', th: 'Valuation แพงหรือถูก?' },
  revenue_label:     { en: 'Revenue',               th: 'รายได้' },
  gross_profit_label: { en: 'Gross profit',         th: 'กำไรขั้นต้น' },
  operating_income_label: { en: 'Operating income', th: 'กำไรดำเนินงาน' },
  net_income_label:  { en: 'Net income',            th: 'กำไรสุทธิ' },
  eps_label:         { en: 'EPS',                   th: 'กำไรต่อหุ้น' },
  fcf_label:         { en: 'Free cash flow',        th: 'กระแสเงินสดอิสระ' },
  revenue_legend:    { en: 'Revenue',               th: 'รายได้' },
  opinc_legend:      { en: 'Operating Income',      th: 'กำไรดำเนินงาน' },
  netinc_legend:     { en: 'Net Income',            th: 'กำไรสุทธิ' },
  items_label:       { en: 'Item',                  th: 'รายการ' },
  financials_foot:   { en: 'Value unit: in local currency units · EPS = per share · “—” = undisclosed/no data', th: 'หน่วยมูลค่า: ตามสกุลเงินท้องถิ่น · EPS = ต่อหุ้น · “—” = ไม่เปิดเผย/ไม่มีข้อมูล' },
  margin_legend_gross: { en: 'Gross Margin',        th: 'ขั้นต้น' },
  margin_legend_operating: { en: 'Operating Margin', th: 'ดำเนินงาน' },
  margin_legend_net:   { en: 'Net Margin',          th: 'สุทธิ' },
  improved_lbl:      { en: 'improved',              th: 'ดีขึ้น' },
  declined_lbl:      { en: 'declined',              th: 'แย่ลง' },
  margin_of_rev_lbl: { en: 'Margin trend (% of revenue)', th: 'อัตรากำไรเทียบยอดขาย (% of revenue)' },
  no_gross_margin_note: { en: 'Gross profit not disclosed separately — showing operating and net margin.', th: 'บริษัทไม่เปิดเผยกำไรขั้นต้น (gross profit) แยกต่างหาก — แสดงเฉพาะอัตรากำไรดำเนินงานและสุทธิ' },
  valuation_title:   { en: 'Valuation',             th: 'มูลค่าหุ้น' },
  valuation_subtitle: { en: 'vs 5-year historical ranges & peers', th: 'เทียบช่วง 5 ปี & peers' },
  legend_current:    { en: 'Current',               th: 'ปัจจุบัน' },
  legend_avg5y:      { en: '5Y Average',            th: 'เฉลี่ย 5 ปี' },
  legend_peer:       { en: 'Peers',                 th: 'peer' },
  min_label:         { en: 'Low',                   th: 'ต่ำสุด' },
  max_label:         { en: 'High',                  th: 'สูงสุด' },
  avg5y_label:       { en: '5Y Avg',                th: 'เฉลี่ย5ปี' },
  balance_sheet_title: { en: 'Balance Sheet Health', th: 'สุขภาพงบดุล' },
  strength_score:    { en: 'Financial Strength Score', th: 'คะแนนความแข็งแกร่ง' },
  bal_very_strong:   { en: 'Very Strong',           th: 'แข็งแกร่งมาก' },
  bal_strong:        { en: 'Strong',                th: 'แข็งแกร่ง' },
  bal_neutral:       { en: 'Neutral',               th: 'ปานกลาง' },
  bal_weak:          { en: 'Weak',                  th: 'ระวัง' },
  analyst_consensus_title: { en: 'Analyst Consensus', th: 'มุมมองนักวิเคราะห์' },
  analyst_firms_unit: { en: 'firms',                th: 'สำนัก' },
  recommendations_lbl: { en: 'Recommendations',     th: 'คำแนะนำ' },
  avg_target:        { en: 'Avg target',            th: 'ราคาเป้าหมายเฉลี่ย' },
  from_current_price: { en: 'from current price',   th: 'จากราคาปัจจุบัน' },
  vs_avg_target:     { en: 'vs avg target',          th: 'เทียบราคาเป้าหมายเฉลี่ย' },
  vs_target_short:   { en: 'vs target',              th: 'เทียบเป้าหมาย' },
  low_label:         { en: 'Low',                   th: 'ต่ำ' },
  avg_label:         { en: 'Avg',                   th: 'เฉลี่ย' },
  high_label:        { en: 'High',                  th: 'สูง' },
  target_track_foot: { en: 'Target price range low–high · blue dot shows current price', th: 'เส้นแสดงช่วงราคาเป้าหมาย ต่ำ–สูง · จุดน้ำเงินคือราคา ณ วันที่วิเคราะห์' },
  latest_filing_title: { en: 'Latest Filing Highlights', th: 'ไฮไลต์รายงานล่าสุด' },
  catalysts_title:   { en: 'Growth Catalysts',      th: 'ปัจจัยหนุน' },
  risks_title:       { en: 'Risk Factors',          th: 'ความเสี่ยง' },
  disclaimer_text:   { en: 'Disclaimer: This information is for educational purposes only and does not constitute investment advice. Some data might be mock-up for design illustration. Investors should research carefully. · Price reference as of {analysisDate}', th: 'ข้อจำกัดความรับผิดชอบ (Disclaimer): ข้อมูลและบทวิเคราะห์นี้สร้างขึ้นเพื่อการศึกษาเท่านั้น ไม่ถือเป็นคำแนะนำในการลงทุน ตัวเลขบางส่วนเป็นข้อมูลตัวอย่าง (mock) เพื่อการออกแบบ ผู้ลงทุนควรศึกษาข้อมูลและปรึกษาผู้เชี่ยวชาญก่อนตัดสินใจ · ราคาและตัวเลขอ้างอิง ณ {analysisDate}' },
  back_to_list:      { en: 'Back to stock list',    th: 'กลับไปรายการหุ้น' },
  business_segments_title: { en: 'Business Segments', th: 'ธุรกิจแยกตามส่วนงาน' },
  segment_summary_title: { en: 'Segment Summary',   th: 'สรุปรายส่วนงาน' },
  cheaper_past:      { en: 'Cheaper',               th: 'ถูกกว่าอดีต' },
  pricier_past:      { en: 'Pricier',               th: 'แพงกว่าอดีต' },
  close_avg:         { en: 'Near Avg',              th: 'ใกล้ค่าเฉลี่ย' },
  val_label:         { en: 'Value',                 th: 'มูลค่า' },
  pct_label:         { en: 'Share %',               th: 'สัดส่วน %' },
  disclosure_label:  { en: 'Disclosure quality',    th: 'การเปิดเผย' },
  segment_col:       { en: 'Segment',               th: 'ส่วนงาน' },
  revenue_latest_col: { en: 'Latest Revenue',       th: 'รายได้ล่าสุด' },
  share_col:         { en: 'Share %',               th: 'สัดส่วน' },
  margin_col:        { en: 'Margin %',              th: 'มาร์จิ้น' },
  cagr_5y_col:       { en: 'CAGR 5Y',               th: 'CAGR 5Y' },
  cagr_desc:         { en: 'CAGR = compound annual growth rate of revenue · Margin = operating profit/revenue (when disclosed)', th: 'CAGR = อัตราเติบโตเฉลี่ยต่อปีของรายได้ · มาร์จิ้น = กำไรดำเนินงาน/รายได้ (แสดงเมื่อบริษัทเปิดเผย)' },
  stacked_desc:      { en: 'Share % of each year (100% stacked)', th: 'สัดส่วน % ของแต่ละปี (100% stacked)' },
  value_desc:        { en: 'Value comparison',      th: 'มูลค่าเทียบกัน' },
  op_margin_segments_lbl: { en: 'Segment operating margin (%)', th: 'อัตรากำไรจากการดำเนินงานแต่ละส่วนงาน (%)' },
  rev_growth_segments_lbl: { en: 'Segment YoY revenue growth (%)', th: 'อัตราการเติบโตรายได้ YoY (%)' },
  unit_label:        { en: 'Unit',                  th: 'หน่วย' },
};

// Rating display config.
window.RATINGS = {
  bull:    { label_en: 'Bullish', label_th: 'มุมมองบวก',  emoji: '🟢', cls: 'bull' },
  neutral: { label_en: 'Neutral', label_th: 'เป็นกลาง',   emoji: '🟡', cls: 'neutral' },
  bear:    { label_en: 'Bearish', label_th: 'มุมมองลบ',   emoji: '🔴', cls: 'bear' },
};

// Country flag tags.
window.COUNTRIES = {
  US: { flag: '🇺🇸', label: 'US' },
  KR: { flag: '🇰🇷', label: 'Korea' },
  JP: { flag: '🇯🇵', label: 'Japan' },
  CN: { flag: '🇨🇳', label: 'China' },
  HK: { flag: '🇭🇰', label: 'Hong Kong' },
  TW: { flag: '🇹🇼', label: 'Taiwan' },
};
